import assert from "node:assert/strict";
import { build } from "esbuild";
const memory = new Map();
globalThis.localStorage = { getItem: key => memory.get(key) ?? null, setItem: (key, value) => memory.set(key, value) };
const output = await build({ entryPoints: ["src/utils/workspacePreferences.ts"], bundle: true, write: false, format: "esm", platform: "node" });
const { readLayouts, defaults, readTimer, toggleTimer, elapsedTime, formatTime, workspaceKey, clamp } = await import("data:text/javascript;base64," + Buffer.from(output.outputFiles[0].text).toString("base64"));
const timerKey = workspaceKey("student-1", "problem-1", "timer");
assert.deepEqual(readTimer(timerKey), { elapsed: 0, startedAt: null });
let timer = toggleTimer(readTimer(timerKey), 1000);
assert.equal(elapsedTime(timer, 475000), 474000);
assert.equal(formatTime(elapsedTime(timer, 475000)), "00:07:54");
memory.set(timerKey, JSON.stringify(timer));
assert.equal(elapsedTime(readTimer(timerKey), 501000), 500000, "Reload or background tabs must count wall-clock time");
timer = toggleTimer(timer, 501000);
assert.equal(elapsedTime(timer, 999000), 500000, "Paused time must stay unchanged");
timer = toggleTimer(timer, 1000000);
assert.equal(elapsedTime(timer, 1005000), 505000, "Resume must retain previous time");
assert.equal(formatTime(360000000), "100:00:00");
assert.equal(elapsedTime({ elapsed: 0, startedAt: null }), 0);
assert.notEqual(timerKey, workspaceKey("student-2", "problem-1", "timer"));
assert.notEqual(timerKey, workspaceKey("student-1", "problem-2", "timer"));
assert.notEqual(workspaceKey("a:b", "c", "notes"), workspaceKey("a", "b:c", "notes"));
assert.equal(readTimer(workspaceKey("student-2", "problem-1", "timer")).elapsed, 0);
const layoutKey = workspaceKey("student-1", "preferences", "layouts");
const preferences = readLayouts(layoutKey);
assert.equal(preferences.layout, "Default");
assert.deepEqual(preferences.sizes, defaults);
preferences.layout = "Note-taking";
preferences.sizes.Default = { ...preferences.sizes.Default, problemWidth: 40, editorHeight: 70 };
preferences.sizes["Note-taking"] = { problemWidth: 32, secondBoundary: 72, editorHeight: 48 };
memory.set(layoutKey, JSON.stringify(preferences));
assert.deepEqual(readLayouts(layoutKey), preferences, "Every layout must restore its independent panel sizes");
memory.set(layoutKey, JSON.stringify({ layout: "invalid", sizes: { Leet: { problemWidth: 99, secondBoundary: 0, editorHeight: 999 } } }));
const safe = readLayouts(layoutKey);
assert.equal(safe.layout, "Default");
assert.equal(safe.sizes.Leet.problemWidth, 18);
assert.equal(safe.sizes.Leet.secondBoundary, 44);
assert.equal(safe.sizes.Leet.editorHeight, 75);
assert.equal(clamp(-100, 18, 50), 18);
assert.equal(clamp(100, 18, 50), 50);
for (const corrupt of ["bad JSON", "null", "{}", '{"elapsed":-1,"startedAt":"invalid"}']) {
  memory.set(timerKey, corrupt); assert.deepEqual(readTimer(timerKey), { elapsed: 0, startedAt: null });
}
memory.set(layoutKey, "bad JSON");
assert.deepEqual(readLayouts(layoutKey).sizes, defaults);
globalThis.localStorage = { getItem() { throw Error("Storage blocked"); } };
assert.deepEqual(readTimer(timerKey), { elapsed: 0, startedAt: null });
assert.equal(readLayouts(layoutKey).layout, "Default");
console.log("PASS: timer pause/resume, reload/background accuracy, user/problem isolation, per-layout sizes, bounds and corrupt/unavailable storage.");
